### ISSUE TITLE
Can't see zsh suggestion

### ISSUE THREAD

**Issue by luis-solano-coda** [catppuccin/alacritty#1]
Hey! I have oh my zsh installed along with zsh-autosuggestion plugin, unfortunately for me I can barely read when an autosuggesstion is there:
![image](https://user-images.githubusercontent.com/93535728/141499947-f5653f54-26b4-4b5a-a8fe-e1dc62505cb9.png)

**Comment by LuisxSullivaN** [comment]
lol I didn't realize I was on my job account, but it's me

**Comment by Pocco81** [comment]
No worries! does it look good now?

**Comment by LuisxSullivaN** [comment]
Yeah a bit better now:
![image](https://user-images.githubusercontent.com/29529436/141656721-890da8a6-963b-4bd2-90d2-2ea811270d72.png)
Thanks!

**Comment by pwsandoval** [comment]
What theme is used in your screenshot?
