### ISSUE TITLE
Highlighted Text Nearly Illegible

### ISSUE THREAD

**Issue by Duder963** [catppuccin/alacritty#15]
Whenever text is highlighted there is little contrast between the text and the highlight, making it incredibly difficult to see the text

Stock alacritty config w/ colors and stock vim

![image](https://user-images.githubusercontent.com/44327643/205458697-69f75b8e-692e-425a-ab14-8c9fb8e4a76c.png)

**Comment by eycer1995** [comment]
Same issue, any workarounds? or just change from terminal emulator?

![Screenshot_20230223_000205](https://user-images.githubusercontent.com/6075113/220812674-d53bac2e-568b-4e80-a005-0d9dd866358d.png)

This is using the `.yml` files as the instructions in the README.

I also tried the vim config (while removing the alacritty.yml config) and got similar result to this [issue](https://github.com/catppuccin/vim/issues/12), for all flavors.

**Comment by nonetrix** [comment]
That makes it worse for me for some reason

With:
![image](https://user-images.githubusercontent.com/45698918/221106432-9efb840b-3b35-4131-b2cc-a2ed8dc1e994.png)
Without
![image](https://user-images.githubusercontent.com/45698918/221106588-4a286200-2196-444f-a91c-bca28914aa7b.png)
