### ISSUE TITLE
Frappe command + bg colour contrast

### ISSUE THREAD

**Issue by jackfranklin** [catppuccin/alacritty#18]
Hey,

I have enabled the Frappe theme and I'm finding the contrast between the background and the main command text (highlighted in red) not quite enough for my eyes. I have tried to alter the theme file to change the colour of the command, but any colour I tried had no effect. Do you know which colour I need to change, or if I could override this to just make the blue text a little lighter?

![catpuccincolor](https://user-images.githubusercontent.com/193238/233590269-36ca4621-848c-4623-b35e-dd726fed55b5.png)

Thanks!

**Comment by andreasgrafen** [comment]
Hmm.. it seems like fish is overriding the colours set by the theme here. I'm not really sure as to why this would happen as I'm not that well versed with fish, but I can't reproduce this issue on my end (using the stock fish experience).
Maybe some setting in your fish.config sets these colours separately?
I'll try to investigate further on my own as well.

<img width="145" alt="Screenshot 2023-04-21 at 12 44 47" src="https://user-images.githubusercontent.com/35840154/233617088-fa4938fe-ae75-4b7d-a339-879f85934085.png">

**Comment by isabelroses** [comment]
> Hmm.. it seems like fish is overriding the colours set by the theme here. I'm not really sure as to why this would happen as I'm not that well versed with fish, but I can't reproduce this issue on my end (using the stock fish experience). Maybe some setting in your fish.config sets these colours separately? I'll try to investigate further on my own as well.

If this is a fish issue, you can use [catppuccin/fish](https://github.com/catppuccin/fish).
Seen as how this is the setup I use and don't have any issues with the colour getting altered.

**Comment by andreasgrafen** [comment]
Ah.. great point! I totally forgot that we have a fish repo!

**Comment by jackfranklin** [comment]
Adding the fish theme worked, thanks! I would guess that fish tries to come up with nice colours based on the terminal theme, or something? Who knows, but it looks much nicer now.
