### ISSUE TITLE
Wrong colors on Zellij's tab bar and status bar

### ISSUE THREAD

**Issue by sebastiancarlos** [catppuccin/alacritty#19]
Using default config in both alacritty and zellij. macOS

<img width="1440" alt="Screenshot 2023-05-09 at 10 13 24" src="https://user-images.githubusercontent.com/88276600/237036533-49bfb37e-a228-4ad0-b344-72ab9f70d88e.png">

**Comment by nekowinston** [comment]
Please see the workaround for Tmux, the same thing would apply to other things using truecolor output.
