### ISSUE TITLE
Outdated Format

### ISSUE THREAD

**Issue by Incompleteusern** [catppuccin/alacritty#20]
I think Alacritty uses .toml now?

**Comment by isabelroses** [comment]
It appears that @Incompleteusern is correct:
https://github.com/alacritty/alacritty#configuration

But I think we should leave the `yml` files in for backwards compatablity.

**Comment by monochromeParasol** [comment]
@isabelroses  @Incompleteusern Hello there. It looks like doing `alacritty migrate -c <path-to-catppuccin-yaml>` works fine. Just tried that on v0.13.0 and it worked for me. The only caveat is the warning for 
`Unused config key: footer_bar`.
After commenting this part of migrated toml, the warning disappeared
```
#[colors.search.footer_bar]
#background = "#6C6F85"
#foreground = "#EFF1F5"
```

**Comment by monochromeParasol** [comment]
@nekowinston thanks a lot!

**Comment by NicolasPerl** [comment]
<img width="1545" alt="Screenshot 2024-02-25 at 9 17 39 PM" src="https://github.com/catppuccin/alacritty/assets/12616774/d4e1cc5e-e852-40a2-9ae0-40c9be2dcf8c">

When I comment out the following code:
```
#[colors.search.footer_bar]
#background = "#6C6F85"
#foreground = "#EFF1F5"
```

I get an error. I'm trying to remove the warning "Unused config key: footer_bar", but am unable to. 

Anyone have any idea what's going on?
