### ISSUE TITLE
alacritty catppuccin-macchiato.yml + ipython unreadable

### ISSUE THREAD

**Issue by kaldown** [catppuccin/alacritty#25]
I have catppuccin-macchiato.yml import and use Alacritty.
Unfortunately it's not readable template to use IPython:
is there any smoother solutions?

<img width="606" alt="Screenshot 2023-11-09 at 10 04 38" src="https://github.com/catppuccin/alacritty/assets/3754017/905825f1-2b4c-4462-bfea-40c9b6b70673">

**Comment by nekowinston** [comment]
This is consistent across other Terminal emulators, it looks like you'd have to set up the [Terminal Colors for IPython](https://ipython.readthedocs.io/en/stable/config/details.html#terminal-colors). Might be worth a separate port.

**Comment by backwardspy** [comment]
hey, i've just updated the catppuccin/python docs with an example of how to get the colours into ipython. https://github.com/catppuccin/python/blob/main/README.md#ipython

let me know if you run into any trouble with it :)

**Comment by kaldown** [comment]
Thank you for that, but it's a bit complicated.
I want to use terminal and catpuccin globally, and I can use IPython globally. But in order to use catpuccin in this case I have to install it in an environment.

Is there any other solution to use catpuccin from path, rather than install it in every project?

**Comment by backwardspy** [comment]
it should work if you install it globally in the same way you have installed ipython. that's how i use it!

**Comment by kaldown** [comment]
I just realised that my global IPython is 3.11, but my project env is 3.8 version of python. Guess the questions remains - is there any solution to point to the repo with catpuccin, instead of a python package?

**Comment by backwardspy** [comment]
unfortunately, this is just how ipython works.

the best i can think of as a truly portable alternative is just to define the style yourself. i cobbled this together by ripping it out of our python port:

```python
from pygments.style import Style
from pygments.token import (
    Comment,
    Error,
    Generic,
    Keyword,
    Literal,
    Name,
    Number,
    Operator,
    Punctuation,
    String,
    Text,
    Token,
)

base = "#1e1e2e"
mantle = "#181825"
text = "#cdd6f4"
red = "#f38ba8"
mauve = "#cba6f7"
peach = "#fab387"
blue = "#89b4fa"
teal = "#94e2d5"
yellow = "#f9e2af"
sky = "#89dceb"
green = "#a6e3a1"
overlay0 = "#9399b2"

class MochaStyle(Style):
    background_color = base
    line_number_background_color = mantle
    line_number_color = text
    styles = {
        Token: text,
        Text: text,
        Error: red,
        Keyword: mauve,
        Keyword.Constant: peach,
        Keyword.Declaration: blue,
        Keyword.Namespace: teal,
        Keyword.Pseudo: mauve,
        Keyword.Reserved: mauve,
        Keyword.Type: blue,
        Name: peach,
        Name.Attribute: blue,
        Name.Constant: yellow,
        Name.Decorator: blue,
        Name.Function: blue,
        Name.Function.Magic: sky,
        Name.Label: blue,
        Name.Tag: mauve,
        Literal: text,
        String: green,
        Number: peach,
        Punctuation: text,
        Operator: sky,
        Comment: overlay0,
        Generic.Heading: f"{blue} bold",
    }

c.TerminalInteractiveShell.highlighting_style = MochaStyle
```

it's not pretty, but it works.

**Comment by kaldown** [comment]
Thank you for the provided class!

[Catpuccin-mochiato](https://github.com/catppuccin/python/blob/main/README.md#ipython) and this example are showing the same results, that are hardly readable.

<img width="248" alt="Screenshot 2023-11-09 at 22 18 31" src="https://github.com/catppuccin/alacritty/assets/3754017/a3dec8d4-1f32-4239-9553-a53e52b9bfae">

**Comment by backwardspy** [comment]
this was a very weird one, i wasn't able to replicate that on my machine but then i switched to my laptop and had the same problem there. i found one interesting thing, if you set the following option in your config:
```python
c.TerminalInteractiveShell.true_color = True
```
it at least makes the completion legible:
![image](https://github.com/catppuccin/alacritty/assets/289746/e9748be3-ca56-44e4-b2fb-b0e1f1a739a6)
with that set, it now looks the same as it always has on my main machine.

i have been trying to find a way to theme this dropdown properly, with no success. i will keep looking, but hopefully that makes it usable for now!

**Comment by kaldown** [comment]
That exactly did the trick and your solution works as well globally.
Thank you very much.
