### ISSUE TITLE
What type-face/font is used in the screenshots?

### ISSUE THREAD

**Issue by johnnymatthews** [catppuccin/alacritty#30]
I just wanna know what type-face is being used in the screenshots of this repo? I'm assuming they're some kind of Nerd Font, but I'm not sure which one:

<img width="1019" alt="image" src="https://github.com/catppuccin/alacritty/assets/9611008/74952b19-834d-4146-a619-b66430650d93">

**Comment by andreasgrafen** [comment]
Since these previews are by @sgoudham I think it should be [be5invis/Iosevka: Versatile typeface for code, from code.](https://github.com/be5invis/Iosevka).
