### ISSUE TITLE
screenshot config

### ISSUE THREAD

**Issue by rileyxz** [catppuccin/alacritty#6]
hey, i would like to know what is the neofetch configuration in the [screenshot](https://github.com/catppuccin/alacritty/raw/main/assets/screenshot.png)

**Comment by wackwack** [comment]
https://github.com/anhsirk0/fetch-master-6000
I believe this is the fetch program, not neofetch

**Comment by nekowinston** [comment]
It's [this](https://github.com/andreasgrafen/pfetch-with-kitties) version of pfetch, specifically.

**Comment by rileyxz** [comment]
> It's [this](https://github.com/andreasgrafen/pfetch-with-kitties) version of pfetch, specifically.
